FROM python:3.11.11-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install --no-cache-dir \
    dagster \
    dagster-postgres \
    dagster-docker \
    debugpy

# Add repository code

WORKDIR /opt/dagster/app



RUN apt-get update && apt-get install -y --no-install-recommends git build-essential ssh &&\
    apt-get clean &&\ 
    rm -rf /var/lib/apt/lists/*

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]