FROM python:3.11.11-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Add repository code

WORKDIR /opt/dagster/app


# Run dagster gRPC server on port 4000

EXPOSE 4000

# reqs
RUN apt-get update && apt-get install -y git build-essential
COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /opt/dagster/gtd_ETL/app
# CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "ETL"]
CMD ["sleep", "infinity"]